### ISSUE TITLE
Não calcula o IOF

### ISSUE THREAD

**Issue by lazarocs19** [rendafixa/rendafixa.github.io#100]
Boa tarde! Para aplicações de renda fixa é necessário calcular o IOF também. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-mDECRETO Nº 6.306, DE 14 DE DEZEMBRO DE 2007
Art. 32.  O IOF será cobrado à alíquota de um por cento ao dia sobre o valor do resgate, cessão ou repactuação, limitado ao rendimento da operação, em função do prazo, conforme tabela constante do Anexo.
§ 1o  O disposto neste artigo aplica-se:
 I - às operações realizadas no mercado de renda fixa;
icrosoft-com:office:word"
xmlns:m="htDECRETO Nº 6.306, DE 14 DE DEZEMBRO DE 2007
Art. 32.  O IOF será cobrado à alíquota de um por cento ao dia sobre o valor do resgate, cessão ou repactuação, limitado ao rendimento da operação, em função do prazo, conforme tabela constante do Anexo.
§ 1o  O disposto neste artigo aplica-se:
 I - às operações realizadas no mercado de renda fixa;
tp://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/186419~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/186419~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/186419~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=PT-BR style='tab-interval:35.4pt;word-wrap:break-word'>

<p class=MsoNormal style='text-align:justify'>DECRETO Nº 6.306, DE 14 DE
DEZEMBRO DE 2007<o:p></o:p></p>

<p class=MsoNormal style='text-align:justify'>Art. 32.<span
style='mso-spacerun:yes'>  </span>O IOF será cobrado à alíquota de um por cento
ao dia sobre o valor do resgate, cessão ou repactuação, limitado ao rendimento
da operação, em função do prazo, conforme tabela constante do Anexo.<o:p></o:p></p>

<p class=MsoNormal style='text-align:justify'>§ 1o<span
style='mso-spacerun:yes'>  </span>O disposto neste artigo aplica-se:<o:p></o:p></p>

<p class=MsoNormal style='text-align:justify'><span
style='mso-spacerun:yes'> </span>I - às operações realizadas no mercado de
renda fixa;<o:p></o:p></p>

Nº de dias | % LIMITE DO RENDIMENTO | Nº de dias | % LIMITE DO RENDIMENTO
-- | -- | -- | --
01 | 96 | 16 | 46
02 | 93 | 17 | 43
03 | 90 | 18 | 40
04 | 86 | 19 | 36
05 | 83 | 20 | 33
06 | 80 | 21 | 30
07 | 76 | 22 | 26
08 | 73 | 23 | 23
09 | 70 | 24 | 20
10 | 66 | 25 | 16
11 | 63 | 26 | 13
12 | 60 | 27 | 10
13 | 56 | 28 | 06
14 | 53 | 29 | 03
15 | 50 | 30 | 00

</body>

</html>

**Comment by marcelorodrigo** [comment]
@lazarocs19 as aplicações de renda fixa, exceto poupança que não tem rendimento antes do aniversário, sofrem tributação de IOF.

Essa situação passou a ocorrer na calculadora quando implementamos o cálculo de aplicações com menos de um mês #64. Você pode abrir um pull request com a implementação do cálculo conforme você apresentou na tabela acima?
