### ISSUE TITLE
[BUG] Label de rendimento erradas

### ISSUE THREAD

**Issue by Frotas** [rendafixa/rendafixa.github.io#171]
![image](https://github.com/rendafixa/rendafixa.github.io/assets/89676387/b58e06af-0a76-4339-9d60-5aef3ec185f2)
> Imagem da calculadora, como dar para notar os resultados dessa simulação há algo errado.

Encontrei um possível problema, as _labels_ de rendimento bruto e liquida estão invertidas.

**Comment by Ascenio** [comment]
Acho que tá certo mesmo. Investiu 5 mil, daí teve 5149.03 de investimento, mas pagou 772.35 de imposto de renda, totalizando 9376.68.
O campo `rendimento bruto` considera só o valor do rendimento, não inclui o valor investido.
