### ISSUE TITLE
[vai mudar?]  o Heroku vai deixar de ser gratuito em Novembro/22

### ISSUE THREAD

**Issue by fabvon** [rendafixa/rendafixa.github.io#37]
Vocês vão continuar na plataforma ou vai migrar? Apenas não quero perder o acesso, adoro o app de vocês

**Comment by marcelorodrigo** [comment]
Ola @fabvon 
A ideia de migrar para o Github usando Github Pages é justamente para manter o projeto ativo e acessível gratuitamente a todos.

https://rendafixa.github.io
