### ISSUE TITLE
Erro de cálculo de imposto

### ISSUE THREAD

**Issue by leobopp** [rendafixa/rendafixa.github.io#51]
A alíquota de IR é cobrada em função dos dias corridos em que o recurso ficou investido e não pelo número de meses.
Até 180 dias: 22,5% sobre o rendimento. 
Entre 181 e 360: 20%
Entre 361 e 720: 17,5%
Acima de 720: 15% sobre o rendimento.

Ao escolher 24 meses, o sistema está aplicando erroneamente a alíquota de 17,5%.
Entretanto, o período de 24 meses terá obrigatoriamente 730 ou 731 dias, o que leva a aplicação da menor alíquota (15%).

**Comment by marcelorodrigo** [comment]
> Até 180 dias: 22,5% sobre o rendimento.
> Entre 181 e 360: 20%
> Entre 361 e 720: 17,5%
> Acima de 720: 15% sobre o rendimento.

Essa alíquota de IR sobre investimentos de renda fixa está corretíssima.
Porém, a calculadora trabalha com meses, e não dias. A situação apresentada também vai ocorrer quando 6 meses for a escolha, porém o investimento tiver 181 dias (muito comum, justamente para evitar a alíquota maior).

A única forma de trabalhar com um cálculo preciso é trabalhando com dias.
Acredito que seria uma ótima funcionalidade de melhoria. Você pode abrir um pull request?

**Comment by leobopp** [comment]
Posso tentar aplicar a melhoria, mas estou enferrujado na programação.

Não tinha nem me dado conta da mesma ocorrência quando escolhido 6 meses.
Entendo que a implementação atual visa deixar a ferramenta muito prática e rápida de usar. 
Cabe avaliar se implementar uma escolha por dias não tornaria a ferramenta menos amigável.

**Comment by RafaDdS** [comment]
Na minha opinião é sempre possível fazer os dois. Que tal manter a interface como está mas adicionar uma aba de opções avançadas que permite colocar a duração do papel em dias? Essa aba poderia ser expandida futuramente.

**Comment by EliaquimNascimento** [comment]
Eu também acredito que seria legal a opção de contar o tempo usando dias também. Uma opção de mudar para dias ou meses
