### ISSUE TITLE
Alíquota de imposto errada

### ISSUE THREAD

**Issue by Josecjr** [rendafixa/rendafixa.github.io#69]
A alíquota de imposto de renda fixa é calculada em dias, tendo os seguintes níveis:
22,5%: até 180 dias;

20,0%: de 181 a 360 dias;

17,5%: de 361 a 720 dias;

15,0%: acima de 720 dias.

Quando selecionamos 24 meses(ou 730 dias), o sistema está aplicando 17.5 % de imposto, quando na verdade deveriam ser 15%. Acredito que o mesmo problema deve ocorrer  para 12 meses(ou 365 dias) ou 6 meses(+-  183 dias). Seria melhor substituir a unidade por dias para evitar confusões.

**Comment by marcelorodrigo** [comment]
@Josecjr o cálculo baseado em meses infelizmente leva a esse tipo de "erro" no cálculo.
#64 resolve esse tipo de cenário habilitando o input em dias, com o cálculo correto!

Obrigado!
